apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-feedback-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-feedback
  template:
    metadata:
      labels:
        app: product-feedback
    spec:
      containers:
        - name: product-feedback
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 3000
