apiVersion: v1
kind: Service
metadata:
  name: product-feedback-service
spec:
  selector:
    app: product-feedback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
