import type { Metadata } from "next";
import { Jost } from "next/font/google";
import type { PropsWithChildren } from "react";

import "~/app/_assets/css/globals.css";
import { Toaster } from "~/app/_components/ui/sonner";
import { cn } from "~/app/_libs/utils";

const fontSans = Jost({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create Next App",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={cn("font-sans", fontSans.variable)}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
