name: Kubernetes Terraform Demo

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: laulauchau/product-feedback-app
  REGISTRY: docker.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Update Terraform variables
        run: |
          echo "image_tag = \"${{ github.sha }}\"" >> terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Verify deployment
        run: |
          minikube kubectl -- get pods
          minikube kubectl -- get services

      - name: Get service URL
        run: |
          minikube service product-feedback-service --url

      - name: Clean up
        if: always()
        run: |
          terraform destroy -auto-approve
          minikube delete
