name: Run tests on master

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
      - uses: actions/checkout@v4

      - name: Load .env file
        uses: falti/dotenv-action@v1
        with:
          path: ./.env
          log-variables: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test
